export const USERS_CLIENT = 'USERS_CLIENT';
export const REQUESTS_CLIENT = 'REQUESTS_CLIENT';
export const TELEMETRY_CLIENT = 'TELEMETRY_CLIENT';
export const CLINICAL_CLIENT = 'CLINICAL_CLIENT';
export const INTEGRATION_CLIENT = 'INTEGRATION_CLIENT';
export const FINANCE_CLIENT = 'FINANCE_CLIENT';
